### PR TITLE
Search in all languages

### PR DESCRIPTION
**Pull request by kevinpark1217**
When searching shows by name, it will also display shows in languages other than English.

### CODE REVIEW

**Comment by kevinpark1217** [comment]
It would be great if you could release a new version after merging this PR, so it could be pushed to places like Nuget.

**Comment by Vannevelj** [comment]
I wasn't aware this was still in use. I have no idea anymore what the API looks like but I will merge it this weekend (sunday at the latest) and update the nuget package.

Thanks for putting this in, Kevin.

**Comment by kevinpark1217** [comment]
Please.
Thanks you.

**Comment by kevinpark1217** [comment]
I realize that you're busy. But, it woiuld be greatly appreciated if you could merge and push the changes to the Nuget.

**Comment by Vannevelj** [comment]
Hi Kevin

I've released a new version just now. Sorry for the delay and thanks again for your contribution!
https://www.nuget.org/packages/TVDBSharp/2.1.0

Jeroen

**Pull request merged**
